[versions]
jdk = "21"
jre = "11"
kotlin = "1.9.20"

[plugins]
dokka = { id = "org.jetbrains.dokka", version.ref = "kotlin" }
kotlinx-kover = "org.jetbrains.kotlinx.kover:0.8.3"
maven-publish = "com.vanniktech.maven.publish.base:0.29.0"
git-publish = "org.ajoberstar.git-publish:4.2.2"
pages = "com.hanggrian.pages:0.1"

[libraries]
# main
kotlinx-coroutines = "org.jetbrains.kotlinx:kotlinx-coroutines-core:1.8.1"
# test
truth = "com.google.truth:truth:1.4.4"
